USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'PMQLNN')
BEGIN
    ALTER DATABASE PMQLNN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PMQLNN;
END
GO

CREATE DATABASE PMQLNN;
GO
